<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc" style="margin-top: 1em;"><ul class="toc-item"><li><span><a href="#点积" data-toc-modified-id="点积-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>点积</a></span></li><li><span><a href="#矩阵乘法" data-toc-modified-id="矩阵乘法-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>矩阵乘法</a></span></li><li><span><a href="#sum" data-toc-modified-id="sum-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>sum</a></span></li></ul></div>

## 点积

In [9]:
import numpy as np
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
x
y
print(x * y) 
print(np.multiply(x, y))

array([[ 1.,  2.],
       [ 3.,  4.]])

array([[ 5.,  6.],
       [ 7.,  8.]])

In [12]:
import numpy as np
x = np.array([[1,2,3,4]], dtype=np.float64)
y = np.array([[5,6,7,8]], dtype=np.float64)
x
y
print(x * y) 
print(np.multiply(x, y))

array([[ 1.,  2.,  3.,  4.]])

array([[ 5.,  6.,  7.,  8.]])

[[  5.  12.  21.  32.]]
[[  5.  12.  21.  32.]]


## 矩阵乘法

In [16]:
import numpy as np
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
x
y
print(x.dot(y)) 
print(np.dot(x, y))

array([[ 1.,  2.],
       [ 3.,  4.]])

array([[ 5.,  6.],
       [ 7.,  8.]])

[[ 19.  22.]
 [ 43.  50.]]
[[ 19.  22.]
 [ 43.  50.]]


In [18]:
import numpy as np
x = np.array([[1,2,3,4]], dtype=np.float64)
y = np.array([[5,6,7,8]], dtype=np.float64)
x
y
print(x.dot(y.T))
print(np.dot(x, y.T))

array([[ 1.,  2.,  3.,  4.]])

array([[ 5.,  6.,  7.,  8.]])

[[ 70.]]
[[ 70.]]


可以理解为两个矩阵，以相同的维度遍历

In [55]:
import numpy as np
embedding = np.array([[1, 2, 3, 10], [4, 5, 6, 10], [7, 8, 9, 10]], dtype=np.int32)
tfidf_sent = np.array([1, 2, 3], dtype=np.int32)

embedding
embedding.shape

tfidf_sent.reshape(1, 3)
tfidf_sent.reshape(1, 3).shape

np.dot(tfidf_sent.reshape(1, 3), embedding)

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 10],
       [ 7,  8,  9, 10]], dtype=int32)

(3, 4)

array([[1, 2, 3]], dtype=int32)

(1, 3)

array([[30, 36, 42, 60]], dtype=int32)

可以看出，权重应该在前

In [84]:
import numpy as np
embedding = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=np.int32)
tfidf_sent = np.array([1, 2, 3], dtype=np.int32)
embedding
tfidf_sent
np.dot(tfidf_sent, embedding)
np.dot(embedding, tfidf_sent)
embedding.T

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)

array([1, 2, 3], dtype=int32)

array([30, 36, 42], dtype=int32)

array([14, 32, 50], dtype=int32)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]], dtype=int32)

## sum

In [72]:
import numpy as np
embedding = np.array([[1, 2, 3, 10], [4, 5, 6, 10], [7, 8, 9, 10]], dtype=np.int32)
embedding
embedding.shape
np.sum(embedding, axis=0)
np.sum(embedding, axis=1)

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 10],
       [ 7,  8,  9, 10]], dtype=int32)

(3, 4)

array([12, 15, 18, 30])

array([16, 25, 34])

In [87]:
embedding.shape

(3, 3)