<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc" style="margin-top: 1em;"><ul class="toc-item"><li><span><a href="#点积" data-toc-modified-id="点积-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>点积</a></span></li><li><span><a href="#矩阵乘法" data-toc-modified-id="矩阵乘法-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>矩阵乘法</a></span></li></ul></div>

## 点积

In [9]:
import numpy as np
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
x
y
print(x * y) 
print(np.multiply(x, y))

array([[ 1.,  2.],
       [ 3.,  4.]])

array([[ 5.,  6.],
       [ 7.,  8.]])

In [12]:
import numpy as np
x = np.array([[1,2,3,4]], dtype=np.float64)
y = np.array([[5,6,7,8]], dtype=np.float64)
x
y
print(x * y) 
print(np.multiply(x, y))

array([[ 1.,  2.,  3.,  4.]])

array([[ 5.,  6.,  7.,  8.]])

[[  5.  12.  21.  32.]]
[[  5.  12.  21.  32.]]


## 矩阵乘法

In [16]:
import numpy as np
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
x
y
print(x.dot(y)) 
print(np.dot(x, y))

array([[ 1.,  2.],
       [ 3.,  4.]])

array([[ 5.,  6.],
       [ 7.,  8.]])

[[ 19.  22.]
 [ 43.  50.]]
[[ 19.  22.]
 [ 43.  50.]]


In [18]:
import numpy as np
x = np.array([[1,2,3,4]], dtype=np.float64)
y = np.array([[5,6,7,8]], dtype=np.float64)
x
y
print(x.dot(y.T))
print(np.dot(x, y.T))

array([[ 1.,  2.,  3.,  4.]])

array([[ 5.,  6.,  7.,  8.]])

[[ 70.]]
[[ 70.]]
